apiVersion: v1
kind: Namespace
metadata:
  name: homeassistant

---

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elchinb-ha-pv
spec:
  capacity:
    storage: 32Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/ydonde/kubernetes/homeassistant/pv/elchinb-pv


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elchinb-ha-pvc
  namespace: homeassistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: elchinb-ha
  namespace: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elchinb-ha
  template:
    metadata:
      labels:
        app: elchinb-ha
    spec:
      containers:
        - name: elchinb-ha
          image: homeassistant/home-assistant
          ports:
            - containerPort: 8123
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: elchinb-ha-pvc

---

# home-assistant-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: elchinb-ha-service
  namespace: homeassistant
spec:
  selector:
    app: elchinb-ha
  ports:
    - protocol: TCP
      port: 8123
      targetPort: 8123
  type: NodePort  # Change to NodePort or ClusterIP based on your setup
